#!/bin/bash
# iterate through all the files in a directory
for file in ~/*
do
#echo $file
if [ -d "$file" ]
then
echo "$file is a directory"
elif [ -f "$file" ]
then
echo "$file is a file"
elif [ -s "$file" ]
then 
	echo "zero size file"

fi
done
